"""add_language_model

Revision ID: 761249ebf49c
Revises: 22834c2775fc
Create Date: 2025-11-21 10:18:01.710311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761249ebf49c'
down_revision: Union[str, Sequence[str], None] = '22834c2775fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('snippets', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'snippets', 'languages', ['language_id'], ['id'])
    op.drop_column('snippets', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'snippets', type_='foreignkey')
    op.drop_column('snippets', 'language_id')
    op.drop_table('languages')
    # ### end Alembic commands ###
